version: 2.1
commands:
  
executors:
  default_exec:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    environment:
      NEW_NAME: Khairah
    executor: default_exec
    steps:
      - checkout
      - run:
          name: 'Build step'
          environment:
            buildId: 1
          command: npm install
      - save_cache:
          key: 'npm-packages'
          paths: 
            - /node_modules
      - run: npm start

  test:
    executor: default_exec
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          command: |
            npm install
            npm test
  
  analyse:
    executor: default_exec
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          command: npm audit fix

workflows:
  workflow-1:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
  