version: 2.1
commands:

orbs:
  aws-cli: circleci/aws-cli@3.1
 
executors:
  default_exec:
    docker:
      - image: circleci/node:13.8.0

jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          command: |
            echo "setting up aws cli?"
            echo "random file to save" >> hello.txt
            BUCKET_EXISTS=$(aws s3api head-bucket --bucket s3://178472627685-testbucket 2>&1 || true)
            if [ -z "$BUCKET_EXISTS" ]; then
              echo "Bucket exists"
            else
              echo "Bucket does not exist"
              aws s3 mb s3://178472627685-testbucket
            aws s3 cp hello.txt s3://178472627685-testbucket           
            echo successful build - $MY_NAME

  # build:
  #   environment:
  #     NEW_NAME: Khairah
  #   executor: default_exec
  #   steps:
  #     - checkout
  #     - run:
  #         name: 'Build step'
  #         environment:
  #           BUILD_ID: 1
  #         command: npm install
  #     - save_cache:
  #         key: 'npm-packages'
  #         paths: 
  #           - /node_modules
  #     - run:
  #         command: |
  #           echo "random file to save" >> hello.txt
  #           aws s3 mb s3://178472627685-testbucket
  #           aws s3 cp hello.txt s3://178472627685-testbucket
  #           echo "successful build - $BUILD_ID"
    

  # test:
  #   executor: default_exec
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: "npm-packages"
  #     - run:
  #         command: |
  #           echo "does this echo? - $CIRCLE_WORKFLOW_ID by $MY_NAME"
  #           npm install
  #           npm test --passWithNoTests
  
  # analyse:
  #   executor: default_exec
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: "npm-packages"
  #     - run:
  #         command: npm audit fix

workflows:
  workflow-1:
    jobs:
      - aws-cli-cred-setup
      # - build:
      #     requires:
      #       - aws-cli-cred-setup
      # - test:
      #     requires:
      #       - build
      # - analyse:
      #     requires:
      #       - test
  